import yaml

from app.main import app


def export_openapi():
    # Fetch the OpenAPI schema generated by FastAPI
    openapi_schema = app.openapi()

    # Save as YAML
    with open("openapi.yaml", "w") as f:
        yaml.dump(openapi_schema, f, sort_keys=False)

    print("Successfully generated openapi.yaml! You can now upload this to editor.swagger.io")


if __name__ == "__main__":
    export_openapi()
